services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - stocky_data:/app/data
    environment:
      - DATABASE_URL=sqlite+pysqlite:///./data/stocky.db
      - SECRET_KEY=your-secret-key-change-in-production-v001
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000"]
      - CREATE_INITIAL_DATA=true
    restart: unless-stopped

volumes:
  stocky_data:

