"""add_upc_data_column

Revision ID: d68fadfe7373
Revises: b4f781f67c01
Create Date: 2026-07-01 08:15:22.429409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68fadfe7373'
down_revision: Union[str, Sequence[str], None] = 'b4f781f67c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('upc_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'upc_data')
    # ### end Alembic commands ###
